Official Project/G4-TaToOr-SE1504-SP22 Official/Controllers/AdminUserController.cs
using G4_TaToOr_SE1504_SP22_Official.Function;
using G4_TaToOr_SE1504_SP22_Official.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G4_TaToOr_SE1504_SP22_Official.Controllers
{
    public class AdminUserController : Controller
    {
        TaToOrEntities context = new TaToOrEntities();
        // GET: AdminUser
        public ActionResult UserManagerIndex(string status)
        {
            // 18 - 22 Filter User, phải là Admin ( 0 ) và id user khác 0 
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if (typeofuser == 0 && userid != 0)
            {
                ViewBag.Status = status;
                var userlist = context.Users.ToList();
                double countDeleted = 0;
                double countAdmin = 0;
                double countStaff = 0;
                double countUser = 0;
                // Vòng lặp đếm các loại tài khoản
                foreach (var get in userlist)
                {
                    if (get.TypeOfUser_ID == 0)
                    {
                        countAdmin += 1;
                    }
                    else if (get.TypeOfUser_ID == 1)
                    {
                        countStaff += 1;
                    }
                    else if (get.TypeOfUser_ID == 2)
                    {
                        countUser += 1;
                    }
                    else { countDeleted += 1; }

                }
                ViewBag.CountDeleted = countDeleted;
                ViewBag.CountAdmin = countAdmin;
                ViewBag.CountStaff = countStaff;
                ViewBag.CountUser = countUser;
                //Hàm tính % trong tổng số
                ViewBag.PercentAdmin = Math.Round(countAdmin / userlist.Count * 100, 2, MidpointRounding.ToEven);
                ViewBag.PercentDeleted = Math.Round(countDeleted / userlist.Count * 100, 2, MidpointRounding.ToEven);
                ViewBag.PercentStaff = Math.Round(countStaff / userlist.Count * 100, 2, MidpointRounding.ToEven);
                ViewBag.PercentUser = Math.Round(countUser / userlist.Count * 100, 2, MidpointRounding.ToEven);
                return View(userlist);
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }
        }

        // GET: AdminUser/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        public ActionResult ThongKeTest()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThongKeTest(Statistical a)
        {

            if (a.value1 < a.value2) // điều kiện nếu giá trị ngày kết thúc ( value 2 ) nhỏ hơn ngày bắt đầu (value 1) thì chạy tập lệnh dướ đây
            {
                DateTime ngaybatdau = a.value1; // Gán giá trị ngày bắt đầu và ngày kết thúc
                DateTime ngayketthuc = a.value2;
                //danh sách lấy ngày hợp lệ giữa ngày bắt đầu và kết thúc
                var listBillAvailable = context.Bills.Where(model => model.Bill_Date >= ngaybatdau && model.Bill_Date <= ngayketthuc).ToList(); // dùng LinQ lấy giá trị giữa ngày bắt đầu và ngày kết thúc
                var listDetailBillAvailable = new List<BillDetail>(); // tạo 1 danh sách chứa các chi tiết của từng đơn
                var listStatisticalDetail = new List<StatisticalDetail>();
                for (int i = 0; i < listBillAvailable.Count; i++)
                {
                    double billID = listBillAvailable[i].Bill_ID;
                    //Danh sách của từng thành phần chi tiết trong đơn hàng chi tiết ( ví dụ Bill ID là 1 có 3 cart detail thì danh sách ngày có 3 phần tử )
                    var listNumberBillDetailAvailable = context.BillDetails.Where(model => model.Bill_ID == billID).ToList();
                    for (int j = 0; j < listNumberBillDetailAvailable.Count; j++)
                    {
                        //thêm từng sản phẩm vào list đó.
                        listDetailBillAvailable.Add(listNumberBillDetailAvailable[j]);
                    }
                }


                for (int i = 0; i < listDetailBillAvailable.Count; i++)
                {

                    string ProductNameiList = listDetailBillAvailable[i].CartDetail.Product.Product_Name.Trim();
                    string Product_Name = listDetailBillAvailable[i].CartDetail.Product.Product_Name.Trim();
                    double Product_Quantity = (double)listDetailBillAvailable[i].CartDetail.CartDetail_QuantityProduct;
                    double Product_TotalMoneyOfProduct = (double)listDetailBillAvailable[i].CartDetail.CartDetail_TotalOfProduct;
                    for (int j = 0; j < i; j++)
                    {
                        // vòng lặp kiểm tra xem có món ăn trùng nhau ko, nếu có tự động vào
                        string ProductNamejList = listDetailBillAvailable[j].CartDetail.Product.Product_Name.Trim();
                        if (ProductNameiList.Equals(ProductNamejList))
                        {
                            Product_Name = ProductNameiList;
                            Product_Quantity += (double)listDetailBillAvailable[j].CartDetail.CartDetail_QuantityProduct;
                            Product_TotalMoneyOfProduct += (double)listDetailBillAvailable[j].CartDetail.CartDetail_TotalOfProduct;
                        }
                    }

                    //if (listStatisticalDetail.Count == 0)
                    //{
                    StatisticalDetail n = new StatisticalDetail();
                    n.Product_Name = Product_Name;
                    n.Product_Quantity = Product_Quantity;
                    n.Product_TotalMoneyOfProduct = Product_TotalMoneyOfProduct;
                    listStatisticalDetail.Add(n);
                    //}
                    //else
                    //{
                    //    StatisticalDetail n = new StatisticalDetail();
                    //    n.Product_Name = ProductNameiList;
                    //    n.Product_Quantity = Product_Quantity;
                    //    n.Product_TotalMoneyOfProduct = Product_TotalMoneyOfProduct;
                    //    for (int k = 0; k < listStatisticalDetail.Count; k++)
                    //    {
                    //        double availablecount = 0;
                    //        if (listStatisticalDetail[k].Product_Name.Equals(ProductNameiList) == true)
                    //        {
                    //            listStatisticalDetail[k].Product_Quantity = Product_Quantity;
                    //            listStatisticalDetail[k].Product_TotalMoneyOfProduct = Product_TotalMoneyOfProduct;
                    //        }
                    //        else if (listStatisticalDetail[k].Product_Name.Equals(ProductNameiList) == false)
                    //        {
                    //            availablecount += 1;
                    //        }
                    //        if (availablecount == k+1)
                    //        {
                    //            listStatisticalDetail.Add(n);
                    //        }
                    //    }
                    //}
                }

                //Sản phẩm bán nhiều nhất: 
                listStatisticalDetail = listStatisticalDetail.GroupBy(model => new { model.Product_Name, model.Product_Quantity, model.Product_TotalMoneyOfProduct }).Select(model => model.First()).ToList();
                listStatisticalDetail = listStatisticalDetail.OrderBy(model => model.Product_Quantity).Reverse().ToList(); // sort theo số lượng
                double BestSeller_Quantity = listStatisticalDetail[0].Product_Quantity;
                double DoanhThu = 0;

                for (int i = 0; i < listStatisticalDetail.Count; i++)
                {
                    DoanhThu += listStatisticalDetail[i].Product_TotalMoneyOfProduct;
                }
                ViewBag.Find = listDetailBillAvailable;
                ViewBag.Detail = listStatisticalDetail;
                ViewBag.Quantity = BestSeller_Quantity;
                ViewBag.value1 = a.value1;
                ViewBag.value2 = a.value2;
                ViewBag.DoanhThu = DoanhThu;
            }

            return View();
        }
        // GET: AdminUser/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateUserbyAdmin()
        {
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if (typeofuser == 0 && userid != 0)
            {
                return View();
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }
        }
        // POST: AdminUser/Create
        [HttpPost]
        public ActionResult CreateUserbyAdmin(User model)
        {
            try
            {
                double typeofuser = 4;
                typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
                double userid = 0;
                userid = Convert.ToDouble(Session["id"]);
                if (typeofuser == 0 && userid != 0)
                {
                    var checkAccount = context.Users.FirstOrDefault(s => s.User_Account == model.User_Account);
                    var checkMail = context.Users.FirstOrDefault(s => s.User_Email == model.User_Email);

                    if (checkAccount == null && checkMail == null)
                    {

                        double idCount = context.Users.Count(); // lấy tổng người dùng
                        Md5 mahoa = new Md5();

Official Project/G4-TaToOr-SE1504-SP22 Official/Views/AdminUser/Delete.cshtml
@model G4_TaToOr_SE1504_SP22_Official.Models.User

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.User_ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_Account)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_Account)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_Password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_Password)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.GenderOfUser_ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.GenderOfUser_ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_DateOfBirth)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_DateOfBirth)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_PhoneNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_PhoneNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TypeOfUser_ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TypeOfUser_ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User_Note)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User_Note)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Official Project/G4-TaToOr-SE1504-SP22 Official/Views/AdminUser/EditUserbyAdmin.cshtml
@model G4_TaToOr_SE1504_SP22_Official.Models.User


@{
    Layout = null;


}


<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Create New User</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="../favicon.ico" type="image/x-icon" />

    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/node_modules/fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/node_modules/ionicons/dist/css/ionicons.min.css">
    <link rel="stylesheet" href="~/node_modules/icon-kit/dist/css/iconkit.min.css">
    <link rel="stylesheet" href="~/node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/dist/css/theme.min.css">
    <script src="~/src/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
    @if (ViewBag.Status != null)
    {
        <script>
            alert("@ViewBag.Status");
        </script>
    }
    <div class="wrapper">
        <header class="header-top" header-theme="light">
            <div class="container-fluid">
                <div class="d-flex justify-content-between">
                    <div class="top-menu d-flex align-items-center">
                        <button type="button" class="btn-icon mobile-nav-toggle d-lg-none"><span></span></button>
                        <div class="header-search">
                            <div class="input-group">
                                <span class="input-group-addon search-close"><i class="ik ik-x"></i></span>
                                <input type="text" class="form-control">
                                <a href="~/AdminUser/UserManagerIndex"><span class="input-group-addon search-btn"> <i class="ik ik-arrow-left"></i> Back to User Management</span></a>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </header>

        <div class="page-wrap">
            <div class="main-content">
                <div class="container-fluid">
                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <i class="ik ik-edit bg-blue"></i>
                                    <div class="d-inline">
                                        <h5>Create New User</h5>
                                        <span>TaToOr System Admin manager</span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    @using (Html.BeginForm())
                    {
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card" style="min-height: 484px;">
                                    <div class="card-body">
                                        @Html.AntiForgeryToken()
                                        @Html.HiddenFor(model => model.User_ID)
                                        @Html.HiddenFor(model => model.User_Account)

                                        <div class="form-group row">
                                            <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Name</label>
                                            <div class="col-sm-9">

                                                <input class="form-control" placeholder="Username" name="User_Name" value="@Model.User_Name" required />
                                                @Html.HiddenFor(model => model.User_Name)
                                                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="exampleInputPassword2" class="col-sm-3 col-form-label">Gender</label>
                                            <div class="col-md-9">
                                                @Html.RadioButtonFor(model => model.GenderOfUser_ID, "0", htmlAttributes: new { @checked = "checked" })
                                                <label>Other</label>
                                                @Html.RadioButtonFor(model => model.GenderOfUser_ID, "1")
                                                <label>Male</label>
                                                @Html.RadioButtonFor(model => model.GenderOfUser_ID, "2")
                                                <label>Female</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="exampleInputPassword2" class="col-sm-3 col-form-label">Birthday</label>
                                            <div class="col-sm-9">
                                                <input class="form-control" placeholder="dd-mm-yyyy" type="date" value="@ViewBag.Year" name="User_DateOfBirth" max="@DateTime.Now.ToString("yyyy-MM-dd")" min="1900-01-01" required />
                                                @Html.HiddenFor(model => model.User_DateOfBirth)
                                                @Html.ValidationMessageFor(model => model.User_DateOfBirth, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Email</label>
                                            <div class="col-sm-9">
                                                <input class="form-control " placeholder="Email" name="User_Email" value="@Model.User_Email" required />
                                                @Html.HiddenFor(model => model.User_Email)
                                                @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })


                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="exampleInputMobile" class="col-sm-3 col-form-label">Phonenumber</label>
                                            <div class="col-sm-9">
                                                <input class="form-control" type="number" placeholder="PhoneNumber" name="User_PhoneNumber" value="@Model.User_PhoneNumber" required min=1 />
                                                @Html.HiddenFor(model => model.User_PhoneNumber)
                                                @Html.ValidationMessageFor(model => model.User_PhoneNumber, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="exampleInputPassword2" class="col-sm-3 col-form-label">Address</label>
                                            <div class="col-sm-9">
                                                <input class="form-control" placeholder="Address" name="User_Address" value="@Model.User_Address" required />
                                                @Html.HiddenFor(model => model.User_Address)
                                                @Html.ValidationMessageFor(model => model.User_Address, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        @if (Model.TypeOfUser_ID == 0)
                                        {
                                            <input type="hidden" name="TypeOfUser_ID" value="@Model.TypeOfUser_ID" />
                                            @Html.HiddenFor(model => model.TypeOfUser_ID)
                                        }
                                        else
                                        { <div class="form-group row">
                                                <label for="exampleInputPassword2" class="col-sm-3 col-form-label">Type Of User</label>
                                                <div class="col-sm-9">
                                                   
                                                    @Html.RadioButtonFor(model => model.TypeOfUser_ID, "1", htmlAttributes: new { @checked = "checked" })
                                                    <label>Staff</label>
                                                    @Html.RadioButtonFor(model => model.TypeOfUser_ID, "2")
                                                    <label>Customer</label>
                                                </div>
                                            </div>}

                                        <div class="form-group row">
                                            <label for="exampleInputPassword2" class="col-sm-3 col-form-label">Note</label>
                                            <div class="col-sm-9">

                                                @Html.EditorFor(model => model.User_Note, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.User_Note, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                        <a class="btn btn-light" href="@Url.Action("UserManagerIndex", "AdminUser")">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>

            </div>
        </div>
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>window.jQuery || document.write('<script src="../src/js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
    <script src="~/dist/js/theme.min.js"></script>
    <script src="~/js/forms.js"></script>
    Google Analytics: change UA-XXXXX-X to be your site's ID.
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l; b[l] || (b[l] =
                function () { (b[l].q = b[l].q || []).push(arguments) }); b[l].l = +new Date;
            e = o.createElement(i); r = o.getElementsByTagName(i)[0];
            e.src = 'https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
    ga('create', 'UA-XXXXX-X', 'auto'); ga('send', 'pageview');</script>
</body>
</html>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}