Official Project/G4-TaToOr-SE1504-SP22 Official/Controllers/ProductManagementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using G4_TaToOr_SE1504_SP22_Official.Models;

namespace G4_TaToOr_SE1504_SP22_Official.Controllers
{
    public class ProductManagementController : Controller
    {
        TaToOrEntities tatoor = new TaToOrEntities();

        // GET: ProductManagement
        public ActionResult ShowAllProduct()
        {
            // khong cho user vao trang quan ly
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {
                var listProduct = new TaToOrEntities().Products.ToList();
                ViewBag.All = tatoor.Products.Count();
                double id = Convert.ToInt32(Session["TypeOfUser"]);
                ViewBag.Id = id;
                ViewBag.SoldOutProduct = listProduct.Where(model => model.ProductStatus_ID == 0).ToList();
                ViewBag.AvailableProduct = listProduct.Where(model => model.ProductStatus_ID == 1).ToList();
                ViewBag.DeletedProduct = listProduct.Where(model => model.ProductStatus_ID == 2).ToList();
                return View(listProduct);
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }      
        }
        // GET: ProductManagement/Details/5
        public ActionResult Details(int id)
        {
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {
                return View();
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }

           
        }

        public ActionResult CreateNewProduct()
        {
            // khong cho user vao trang quan ly
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {
                return View();
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }

           
        }

        // POST: ProductManagement/Create
        [HttpPost]
        public ActionResult CreateNewProduct(Product model1)
        {
            try
            {
                // TODO: Add insert logic here
                var context = new TaToOrEntities();
                context.Products.Add(model1);
                float idcount = context.Products.Count();
                model1.Product_ID = idcount + 1;
                model1.Product_Star = 0;
                model1.ProductStatus_ID = 1;
                context.SaveChanges();
                return RedirectToAction("ShowAllProduct");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductManagement/Edit/5
        public ActionResult EditProduct(int id)
        {
            // khong cho user vao trang quan ly
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {

                double type = Convert.ToInt32(Session["TypeOfUser"]);
                ViewBag.Id = type;
                var context = new TaToOrEntities();
                var editing = context.Products.Find(id);
                editing.Product_Name = editing.Product_Name.Trim();
                editing.Product_Description = editing.Product_Description.Trim();

                return View(editing);
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }


        }

        // POST: ProductManagement/Edit/5
        [HttpPost]
        public ActionResult EditProduct(Product model)
        {
            try
            {
                // TODO: Add update logic here
                double type = Convert.ToInt32(Session["TypeOfUser"]);
                ViewBag.Id = type;
                var context = new TaToOrEntities();
                var editing = context.Products.Find(model.Product_ID);
                editing.Product_Name = model.Product_Name;
                editing.Product_Price = model.Product_Price;
                editing.Product_Description = model.Product_Description;
                editing.Product_Star = model.Product_Star;
                editing.ProductStatus_ID = model.ProductStatus_ID;
                editing.Origin_ID = model.Origin_ID;
                editing.TypeOfFood_ID = model.TypeOfFood_ID;
                editing.FormOfFood_ID = model.FormOfFood_ID;
                context.SaveChanges();
                return RedirectToAction("ShowAllProduct");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductManagement/Delete/5
        // GET: ProductManagement/Delete/5
        public ActionResult DeleteProduct(int id)
        {
            // khong cho user vao trang quan ly
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {

                var context = new TaToOrEntities();
                var deleteing = context.Products.Find(id);
                return View(deleteing);
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }


        }

        // POST: ProductManagement/Delete/5
        [HttpPost]
        public ActionResult DeleteProduct(Product model)
        {
            try
            {
                // TODO: Add delete logic here
                var context = new TaToOrEntities();
                var olditem = context.Products.Find(model.Product_ID);
                olditem.ProductStatus_ID = 2;
                context.SaveChanges();
                return RedirectToAction("ShowAllProduct");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Upload(int id)
        {
            // khong cho user vao trang quan ly
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {

                //var context = new TaToOrEntities();
                //var editing = context.Products.Find(id);

                ViewBag.Pic = tatoor.Pictures.Where(i => i.Product_ID == id).ToList();
                ViewBag.idPro = id;
                return View();
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }

        }


        [HttpGet]
        public ActionResult UploadImage(int id)
        {
            // khong cho user vao trang quan ly
            double typeofuser = 4;
            typeofuser = Convert.ToDouble(Session["TypeOfUser"]);
            double userid = 0;
            userid = Convert.ToDouble(Session["id"]);
            if ((typeofuser == 0 || typeofuser == 1) && userid != 0)
            {

                Session["ID_Product"] = id;
                return View();
            }
            else
            {
                return RedirectToAction("SOS", "Home");
            }

        }


        [HttpPost]
        public ActionResult UploadImage(Picture img)
        {
            var context = new TaToOrEntities();
            //var editing = context.Products.Find(Convert.ToInt32(ID));

            string filename = Path.GetFileNameWithoutExtension(img.ImageFile.FileName);
            string extension = Path.GetExtension(img.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            img.Picture_Link = "../../img/" + filename;
            filename = Path.Combine(Server.MapPath("../../img/"), filename);
            img.ImageFile.SaveAs(filename);
            img.Product_ID = Convert.ToInt32(Session["ID_Product"]);
            float idcount = context.Pictures.Count();

            img.Picture_ID = idcount + 1;
            context.Pictures.Add(img);
            context.SaveChanges();



            ModelState.Clear();
            return RedirectToAction("Upload/" + Session["ID_Product"]);
        }
    }
}

Official Project/G4-TaToOr-SE1504-SP22 Official/Views/ProductManagement/CreateNewProduct.cshtml
@model G4_TaToOr_SE1504_SP22_Official.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Create New Product</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="icon" type="image/png" href="../../img/logo/logo2.png" />
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../node_modules/fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="../node_modules/ionicons/dist/css/ionicons.min.css">
    <link rel="stylesheet" href="../node_modules/icon-kit/dist/css/iconkit.min.css">
    <link rel="stylesheet" href="../node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
    <link rel="stylesheet" href="../dist/css/theme.min.css">
    <script src="../src/js/vendor/modernizr-2.8.3.min.js"></script>
    <style>
        body {
            line-height: 2.5;
            font-size: 1.2rem;
        }

        .btn {
            padding: 6px 18px;
            height: 60px;
            font-size: 23px;
        }
    </style>
</head>

<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="wrapper">
        <header class="header-top" header-theme="light">
            <div class="container-fluid">
                <div class="d-flex justify-content-between">
                    <div class="top-menu d-flex align-items-center">
                        <button type="button" class="btn-icon mobile-nav-toggle d-lg-none"><span></span></button>
                        <div class="header-search">
                            <div class="input-group">
                                <span class="input-group-addon search-close"><i class="ik ik-x"></i></span>
                                <input type="text" class="form-control">
                                <a href="@Url.Action("ShowAllProduct","ProductManagement")"><span class="input-group-addon search-btn"> <i class="ik ik-arrow-left"></i> Back to User Management</span></a>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </header>

        <div class="page-wrap">
            <div class="main-content">
                <div class="container-fluid">
                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h5>Create New Product</h5>
                                        <span>TaToOr System Admin Manager</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    @using (Html.BeginForm())
                    {
                        <div class="row">
                            <div class="col-md-10">
                                <div class="card">
                                    <div class="card-body">
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @*<div class="form-group">
                                                @Html.LabelFor(model => model.Product_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.Product_ID, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Product_ID, "", new { @class = "text-danger" })
                                                </div>
                                            </div>*@
                                        <div class="form-group row">
                                            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(model => model.Product_Price, htmlAttributes: new { @class = "control-label col-md-2"})
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Product_Price, new { htmlAttributes = new { @class = "form-control", Type = "number", @min = "1" } })
                                                @Html.ValidationMessageFor(model => model.Product_Price, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(model => model.Product_Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                <textarea @Html.EditorFor(model => model.Product_Description, new { htmlAttributes = new { @class = "form-control" } })>
                                                
                                                </textarea>

                                                @Html.ValidationMessageFor(model => model.Product_Description, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        @*<div class="form-group">
                                                @Html.LabelFor(model => model.Product_Star, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.Product_Star, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Product_Star, "", new { @class = "text-danger" })
                                                </div>
                                            </div>*@

                                        @*<div class="form-group">
                                                @Html.LabelFor(model => model.ProductStatus_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.ProductStatus_ID, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.ProductStatus_ID, "", new { @class = "text-danger" })
                                                </div>
                                            </div>*@
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.Origin_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.RadioButtonFor(model => model.Origin_ID, "1", htmlAttributes: new { @checked = "checked" })
                                            <label>Vietnam</label>
                                            @Html.RadioButtonFor(model => model.Origin_ID, "2")
                                            <label>Korea</label>
                                            @Html.RadioButtonFor(model => model.Origin_ID, "3")
                                            <label>Thailand</label>
                                            @Html.RadioButtonFor(model => model.Origin_ID, "4")
                                            <label>India</label>
                                            @Html.RadioButtonFor(model => model.Origin_ID, "5")
                                            <label>Japan</label>
                                            @Html.RadioButtonFor(model => model.Origin_ID, "6")
                                            <label>China</label>

                                        </div>
                                    </div>

                                        <div class="form-group row">
                                            @Html.LabelFor(model => model.TypeOfFood_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.RadioButtonFor(model => model.TypeOfFood_ID, "0", htmlAttributes: new { @checked = "checked" })
                                                <label>Main course</label>
                                                @Html.RadioButtonFor(model => model.TypeOfFood_ID, "1")
                                                <label>Desert</label>
                                                @Html.RadioButtonFor(model => model.TypeOfFood_ID, "2")
                                                <label>Pastry</label>
                                                @Html.RadioButtonFor(model => model.TypeOfFood_ID, "3")
                                                <label>Diet</label>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            @Html.LabelFor(model => model.FormOfFood_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.RadioButtonFor(model => model.FormOfFood_ID, "1", htmlAttributes: new { @checked = "checked" })
                                                <label>Liquid</label>
                                                @Html.RadioButtonFor(model => model.FormOfFood_ID, "2")
                                                <label>Dry</label>
                                                @Html.RadioButtonFor(model => model.FormOfFood_ID, "3")
                                                <label>Cold</label>
                                                @Html.RadioButtonFor(model => model.FormOfFood_ID, "4")
                                                <label>Cake</label>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <div class="col-md-10">
                                                <input type="submit" value="Create" class="btn" />
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>

            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>window.jQuery || document.write('<script src="..Temp/src/js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="../node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
    <script src="../dist/js/theme.min.js"></script>
    <script src="../js/forms.js"></script>
    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l; b[l] || (b[l] =
                function () { (b[l].q = b[l].q || []).push(arguments) }); b[l].l = +new Date;
            e = o.createElement(i); r = o.getElementsByTagName(i)[0];
            e.src = 'https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
    ga('create', 'UA-XXXXX-X', 'auto'); ga('send', 'pageview');</script>
</body>
</html>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Official Project/G4-TaToOr-SE1504-SP22 Official/Views/ProductManagement/Upload.cshtml
@model G4_TaToOr_SE1504_SP22_Official.Models.Picture



@{
    ViewBag.Title = "Upload";
    Layout = null;
}

<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>TaToOr - Product Management</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="../../img/logo/logo2.png" />

    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/node_modules/fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/node_modules/icon-kit/dist/css/iconkit.min.css">
    <link rel="stylesheet" href="~/node_modules/ionicons/dist/css/ionicons.min.css">
    <link rel="stylesheet" href="~/node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/node_modules/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/node_modules/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="~/node_modules/weather-icons/css/weather-icons.min.css">
    <link rel="stylesheet" href="~/node_modules/c3/c3.min.css">
    <link rel="stylesheet" href="~/node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/node_modules/owl.carousel/dist/assets/owl.carousel.css">
    <link rel="stylesheet" href="~/node_modules/owl.carousel/dist/assets/owl.theme.default.css">
    <link rel="stylesheet" href="~/dist/css/theme.min.css">
    <script src="../src/js/vendor/modernizr-2.8.3.min.js"></script>
    <style>
        .navigation-main {
            background-color: white;
            border-radius: 10px;
        }

        .card-body {
            background-color: white;
        }

        th, td {
            padding: 15px;
            font-size: 120%
        }

        thead {
            text-align: justify;
            background-color: #FFF3E1;
        }

        .app-sidebar {
            color: white;
        }

        .nav-item {
            padding: 3%;
        }
    </style>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="wrapper">


        <div class="page-wrap">
            <div class="app-sidebar" style="background-color: #FFF3E1 ">
                <div class="sidebar-header">

                    <a class="header-brand" href="@Url.Action("Index", "Home")">
                        <div class="logo-img">
                            <img src="~/img/logo/logo2.png" class="header-brand-img" alt="lavalite" idth="80px" height="50px">

                            <span class="text">TaToOr</span>
                        </div>

                    </a>
                    
                </div>

                <div class="sidebar-content">
                    <div class="nav-container">
                        <nav id="main-menu-navigation" class="navigation-main">
                            <div class="nav-lavel" style="color: white; background-color: #945305 "><i class="ik ik-settings"></i>Admin Management</div>
                            <div class="nav-item ">
                                <a href="@Url.Action("UserManagerIndex", "AdminUser")" style="color:orange; font-weight: bold"><i class="ik ik-user-plus"></i>User Management</a>
                            </div>
                            <div class="nav-item active">
                                <a href="@Url.Action("ShowAllProduct", "ProductManagement")" style="color: orange; font-weight: bold "><i class="ik ik-archive"></i>Product Management</a>
                            </div>
                            <div class="nav-item ">
                                <a href="@Url.Action("ShowAllBill", "BillManagement")" style="color: orange; font-weight: bold "><i class="ik ik-shopping-cart"></i>Order Management</a>
                            </div>
                            <div class="nav-item ">
                                <a href="@Url.Action("ReviewIndex", "Review")" style="color: orange; font-weight: bold "><i class="ik ik-message-circle"></i><span>Review Management</span></a>
                            </div>
                            <div class="nav-item ">
                                <a href="@Url.Action("Index", "Statistical")" style="color: orange; font-weight: bold "><i class="ik ik-bar-chart-2" style="color: orange"></i><span>Statistic Management</span></a>
                            </div>

                        </nav>
                    </div>
                </div>
            </div>

            <div class="main-content">
                <div class="container" style="font-size: 200%; padding-bottom: 5%">
                    <a href="@Url.Action("ShowAllProduct", "ProductManagement")"><i class="ik ik-skip-back"></i><span>Back</span></a>
                </div>
                <div class="container">

                    @foreach (var list in ViewBag.Pic)
                    {
                        <div class="row" style="display: inline-block; padding:1%">
                            <div class="col-lg-3">
                                <div class="image_col">
                                    <img src="@list.Picture_Link" alt="IMG-BANNER" class="img" style=" width: 200px; height: 200px" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
                @*<div class="container">
                        @Html.ActionLink("Upload image", "UploadImage", new { id = @ViewBag.idPro })
                    </div>*@
                <div class="container">
                    <div class="row" style=" padding-top: 10%">
                        <div class="col-lg-4" style="font-size: 200%">
                            @Html.ActionLink("Upload image", "UploadImage", new { id = @ViewBag.idPro })
                        </div>
                    </div>
                </div>
            </div>



            <footer class="footer">
                <div class="w-100 clearfix">
                    <span class="text-center text-sm-left d-md-inline-block">Copyright © 2018 ThemeKit v2.0. All Rights Reserved.</span>
                    <span class="float-none float-sm-right mt-1 mt-sm-0 text-center">Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://lavalite.org/" class="text-dark" target="_blank">Lavalite</a></span>
                </div>
            </footer>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>window.jQuery || document.write('<script src="../src/js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="../node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
    <script src="../node_modules/screenfull/dist/screenfull.js"></script>
    <script src="../node_modules/moment/moment.js"></script>
    <script src="../node_modules/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="../node_modules/jvectormap/jquery-jvectormap.min.js"></script>
    <script src="../node_modules/jvectormap/tests/assets/jquery-jvectormap-world-mill-en.js"></script>
    <script src="../dist/js/theme.min.js"></script>
    <script src="../js/widgets.js"></script>
    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l; b[l] || (b[l] =
                function () { (b[l].q = b[l].q || []).push(arguments) }); b[l].l = +new Date;
            e = o.createElement(i); r = o.getElementsByTagName(i)[0];
            e.src = 'https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
    ga('create', 'UA-XXXXX-X', 'auto'); ga('send', 'pageview');
    </script>
</body>
</html>